sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5-dev"
  - "pypy"
  - "pypy3"
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install twine
script: coverage run --source=twitter setup.py test
after_success: coveralls
deploy:
  provider: pypi
  user: joamag
  password:
    secure: iZ0VZjLF6yOoJzkPswdVsXksOjlsQeujK6wJTzLvaJVqXtJV2YvbmBhIY1HiUXqGyUwgVJuWmzACZB5RtoFyfHUZ8kArQ8xceHJU2HhWtWnvfTRT5IbszrXS+EZ3qiexMDc3c/fI0GPbNyZvPAbXYSOAS8cJ0jY/EEa8rFq2dTQ=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "2.7"
